//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Additional_Facility_Details
    {
        public int Facility_ID { get; set; }
        public string Facility_Name { get; set; }
        public string Facility_Address { get; set; }
        public long Facility_Contact { get; set; }
        public int Facility_Availability { get; set; }
        public long Facility_Charges { get; set; }
    }
}
