//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminRegistration
    {
        public int Admin_ID { get; set; }
        public string Admin_Name { get; set; }
        public string Admin_Password { get; set; }
    }
}
