//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guard_Duty
    {
        public Guard_Duty()
        {
            this.Parking_Details = new HashSet<Parking_Details>();
        }
    
        public int Visitor_ID { get; set; }
        public string Visitor_Name { get; set; }
        public string In_Datetime { get; set; }
        public string Out_Datetime { get; set; }
        public string Details { get; set; }
        public string House_ID { get; set; }
        public Nullable<int> Require { get; set; }
    
        public virtual House_Details House_Details { get; set; }
        public virtual ICollection<Parking_Details> Parking_Details { get; set; }
    }
}
