//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public House()
        {
            this.Guard_Duty = new HashSet<Guard_Duty>();
            this.OwnerRegistrations = new HashSet<OwnerRegistration>();
        }
    
        public string House_ID { get; set; }
        public int House_Size_BHK { get; set; }
        public string House_Type { get; set; }
    
        public virtual ICollection<Guard_Duty> Guard_Duty { get; set; }
        public virtual ICollection<OwnerRegistration> OwnerRegistrations { get; set; }
    }
}
