//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nearby_Services_Category
    {
        public Nearby_Services_Category()
        {
            this.Nearby_Services = new HashSet<Nearby_Services>();
        }
    
        public int Nearby_Services_Category_ID { get; set; }
        public string Nearby_Services_Category1 { get; set; }
    
        public virtual ICollection<Nearby_Services> Nearby_Services { get; set; }
    }
}
