//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Category
    {
        public Service_Category()
        {
            this.User_Service_Details = new HashSet<User_Service_Details>();
        }
    
        public int Service_Category_ID { get; set; }
        public string Service_Category1 { get; set; }
    
        public virtual ICollection<User_Service_Details> User_Service_Details { get; set; }
    }
}
