//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Society
    {
        public Society()
        {
            this.OwnerRegistrations = new HashSet<OwnerRegistration>();
        }
    
        public string Society_ID { get; set; }
        public string Society_Name { get; set; }
        public string Society_City { get; set; }
        public long Society_Pincode { get; set; }
        public int Society_NoOffHouse { get; set; }
    
        public virtual ICollection<OwnerRegistration> OwnerRegistrations { get; set; }
    }
}
